import '@/assets/styles/globals.css'
import AppProviders from '@/components/layout/providers/app-providers'
import WebVitals from '@/components/layout/web-vitals'
import { Toaster } from '@/components/ui/sonner'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import React from 'react'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <WebVitals />
        <AppProviders>
          {children}
          <Toaster richColors position="top-right" closeButton />
        </AppProviders>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
